# set up osc server
ATARI_SERVER_IP = "10.6.255.255"
ATARI_SERVER_PORT = 5555

SOUND_SERVER_IP = "127.0.0.1"
SOUND_SERVER_PORT = 6666

ROM_FILE = 'files/roms/rraid.bin'

SERVER_LOCALHOST = "0.0.0.0"
POSE_SERVER_PORT = 12345

MY_SKELETON_ID = 0

POSE_DATA_PATH = 'files/data/pose'
POSE_MODELS_PATH = 'files/models/pose'

EMG_DATA_PATH = 'files/data/emg'
EMG_MODELS_PATH = 'files/models/emg'

    
BITALINO_MAC_ADDRESS = "/dev/tty.BITalino-BD-37-Bluetoot" # "98:D3:91:FD:40:4D"

BITALINO_ACQ_CHANNELS = [0] # record A1 
BITALINO_SRATE = 1000

EMG_SEGMENTATION_WINDOW = 250
